### ISSUE TITLE
动态障碍物添加

### ISSUE THREAD

**Issue by EduAkun** [ai-winter/matlab_motion_planning#2]
请问能否可以在运行过程中添加动态障碍物，如果可以添加，应该做出怎样的修改。

**Comment by ai-winter** [comment]
@EduAkun 

Like this?

![a](https://github.com/ai-winter/matlab_motion_planning/assets/61778098/6721101c-12bf-4d2e-9ac5-7c7e8ace93c9)

**Comment by EduAkun** [comment]
yes

**Comment by ai-winter** [comment]
@EduAkun 

You can contact me through the homepage to obtain this version.
